# Generated by Django 5.2.3 on 2025-07-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='join_us_user',
            table='Join_users',
        ),
    ]
